/**
 * Stable, machine-readable error codes (CLAUDE.md §8). The frontend switches on
 * these; never change a value, only add new ones.
 */
export const ErrorCode = {
  // generic
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  NOT_FOUND: 'NOT_FOUND',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  CONFLICT: 'CONFLICT',

  // auth
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  FORBIDDEN: 'FORBIDDEN',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
  USER_INACTIVE: 'USER_INACTIVE',

  // assets
  ASSET_NOT_AVAILABLE: 'ASSET_NOT_AVAILABLE',
  ASSET_ALREADY_ASSIGNED: 'ASSET_ALREADY_ASSIGNED',
  ASSET_NOT_ASSIGNED: 'ASSET_NOT_ASSIGNED',
  INVALID_TRANSITION: 'INVALID_TRANSITION',
  ASSET_TAG_IMMUTABLE: 'ASSET_TAG_IMMUTABLE',
  DUPLICATE_ASSET_TAG: 'DUPLICATE_ASSET_TAG',
  DUPLICATE_SERIAL_NUMBER: 'DUPLICATE_SERIAL_NUMBER',
  SERIAL_REQUIRED: 'SERIAL_REQUIRED',
  STALE_VERSION: 'STALE_VERSION',

  // employees
  EMPLOYEE_EXITED: 'EMPLOYEE_EXITED',
  EMPLOYEE_HAS_OPEN_ASSIGNMENTS: 'EMPLOYEE_HAS_OPEN_ASSIGNMENTS',
  EMPLOYEE_ALREADY_EXITED: 'EMPLOYEE_ALREADY_EXITED',
  DUPLICATE_EMPLOYEE_CODE: 'DUPLICATE_EMPLOYEE_CODE',
  DUPLICATE_EMPLOYEE_EMAIL: 'DUPLICATE_EMPLOYEE_EMAIL',
  SELF_REPORTING_MANAGER: 'SELF_REPORTING_MANAGER',

  // assignments
  ASSIGNMENT_NOT_OPEN: 'ASSIGNMENT_NOT_OPEN',
  TRANSFER_TO_SAME_EMPLOYEE: 'TRANSFER_TO_SAME_EMPLOYEE',

  // masters
  DUPLICATE_RECORD: 'DUPLICATE_RECORD',
  REFERENCED_RECORD_INACTIVE: 'REFERENCED_RECORD_INACTIVE',
  RECORD_IN_USE: 'RECORD_IN_USE',

  // stock (phase 5)
  INSUFFICIENT_STOCK: 'INSUFFICIENT_STOCK',
  STOCK_BALANCE_MISMATCH: 'STOCK_BALANCE_MISMATCH',

  // repairs (phase 6)
  REPAIR_TICKET_ALREADY_OPEN: 'REPAIR_TICKET_ALREADY_OPEN',
  REPAIR_TICKET_CLOSED: 'REPAIR_TICKET_CLOSED',
} as const;
export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
