/**
 * Static reference data for the seed. Kept separate from the generation logic
 * so the interesting part of seed.ts stays readable.
 */

export const LOCATIONS = [
  {
    key: 'ggn-hq',
    name: 'Gurugram HQ',
    type: 'OFFICE' as const,
    city: 'Gurugram',
    address: 'Tower B, Cyber City, DLF Phase 2, Gurugram 122002',
  },
  {
    key: 'ggn-store',
    name: 'Gurugram Store Room',
    type: 'STORE_ROOM' as const,
    city: 'Gurugram',
    address: 'Tower B, Basement 1, Cyber City, Gurugram 122002',
  },
  {
    key: 'blr-office',
    name: 'Bengaluru Office',
    type: 'OFFICE' as const,
    city: 'Bengaluru',
    address: '4th Floor, Embassy Tech Village, Outer Ring Road, Bengaluru 560103',
  },
] as const;

export const VENDORS = [
  {
    name: 'Northstar Technologies Pvt Ltd',
    contactPerson: 'Rohit Malhotra',
    phone: '+91 98110 22345',
    email: 'sales@northstartech.example',
    gstin: '06AABCN1234F1Z5',
    address: 'Plot 21, Udyog Vihar Phase 4, Gurugram 122015',
    isServiceCentre: false,
  },
  {
    name: 'Meridian Infotech Distributors',
    contactPerson: 'Sneha Rao',
    phone: '+91 80456 11987',
    email: 'orders@meridianinfotech.example',
    gstin: '29AACCM5678K1Z2',
    address: '12 Residency Road, Bengaluru 560025',
    isServiceCentre: false,
  },
  {
    name: 'CareFix Authorised Service Centre',
    contactPerson: 'Imran Qureshi',
    phone: '+91 99100 33456',
    email: 'support@carefix.example',
    gstin: '06AADCC9012L1Z8',
    address: 'Shop 7, Sector 14 Market, Gurugram 122001',
    isServiceCentre: true,
  },
  {
    name: 'Southern Peripherals & Repairs',
    contactPerson: 'Lakshmi Narayanan',
    phone: '+91 80223 77654',
    email: 'service@southernperipherals.example',
    gstin: '29AAECS3456M1Z1',
    address: '88 Jayanagar 4th Block, Bengaluru 560011',
    isServiceCentre: true,
  },
] as const;

export const CATEGORIES = [
  {
    key: 'laptop',
    name: 'Laptop',
    code: 'LAP',
    trackingMode: 'SERIALIZED' as const,
    requiresSerial: true,
    defaultUsefulLifeMonths: 48,
  },
  {
    key: 'monitor',
    name: 'Monitor',
    code: 'MON',
    trackingMode: 'SERIALIZED' as const,
    requiresSerial: true,
    defaultUsefulLifeMonths: 60,
  },
  {
    key: 'dock',
    name: 'Docking Station',
    code: 'DOCK',
    trackingMode: 'SERIALIZED' as const,
    requiresSerial: true,
    defaultUsefulLifeMonths: 60,
  },
  {
    key: 'headset',
    name: 'Headset',
    code: 'HEAD',
    trackingMode: 'SERIALIZED' as const,
    requiresSerial: false,
    defaultUsefulLifeMonths: 24,
  },
  // The two BULK categories: counted, never serialised (CLAUDE.md §11).
  {
    key: 'charger',
    name: 'Charger',
    code: 'CHG',
    trackingMode: 'BULK' as const,
    requiresSerial: false,
    defaultUsefulLifeMonths: 24,
  },
  {
    key: 'peripheral',
    name: 'Mouse & Keyboard',
    code: 'PER',
    trackingMode: 'BULK' as const,
    requiresSerial: false,
    defaultUsefulLifeMonths: 24,
  },
] as const;

export interface SeedModel {
  key: string;
  categoryKey: (typeof CATEGORIES)[number]['key'];
  manufacturer: string;
  modelName: string;
  specs: Record<string, string | number | boolean>;
  defaultWarrantyMonths: number;
}

export const MODELS: SeedModel[] = [
  {
    key: 'lat-5440',
    categoryKey: 'laptop',
    manufacturer: 'Dell',
    modelName: 'Latitude 5440',
    specs: {
      cpu: 'Intel Core i5-1335U',
      ramGb: 16,
      storageGb: 512,
      screenInches: 14,
      os: 'Windows 11 Pro',
    },
    defaultWarrantyMonths: 36,
  },
  {
    key: 'lat-7450',
    categoryKey: 'laptop',
    manufacturer: 'Dell',
    modelName: 'Latitude 7450',
    specs: {
      cpu: 'Intel Core Ultra 7 155U',
      ramGb: 32,
      storageGb: 1024,
      screenInches: 14,
      os: 'Windows 11 Pro',
    },
    defaultWarrantyMonths: 36,
  },
  {
    key: 'tp-t14',
    categoryKey: 'laptop',
    manufacturer: 'Lenovo',
    modelName: 'ThinkPad T14 Gen 4',
    specs: {
      cpu: 'AMD Ryzen 7 PRO 7840U',
      ramGb: 32,
      storageGb: 1024,
      screenInches: 14,
      os: 'Windows 11 Pro',
    },
    defaultWarrantyMonths: 36,
  },
  {
    key: 'tp-e14',
    categoryKey: 'laptop',
    manufacturer: 'Lenovo',
    modelName: 'ThinkPad E14 Gen 5',
    specs: {
      cpu: 'Intel Core i5-1335U',
      ramGb: 16,
      storageGb: 512,
      screenInches: 14,
      os: 'Windows 11 Pro',
    },
    defaultWarrantyMonths: 24,
  },
  {
    key: 'mbp-14',
    categoryKey: 'laptop',
    manufacturer: 'Apple',
    modelName: 'MacBook Pro 14 M3',
    specs: { cpu: 'Apple M3 Pro', ramGb: 18, storageGb: 512, screenInches: 14.2, os: 'macOS' },
    defaultWarrantyMonths: 12,
  },
  {
    key: 'mba-13',
    categoryKey: 'laptop',
    manufacturer: 'Apple',
    modelName: 'MacBook Air 13 M2',
    specs: { cpu: 'Apple M2', ramGb: 16, storageGb: 256, screenInches: 13.6, os: 'macOS' },
    defaultWarrantyMonths: 12,
  },
  {
    key: 'p2422h',
    categoryKey: 'monitor',
    manufacturer: 'Dell',
    modelName: 'P2422H',
    specs: { screenInches: 24, resolution: '1920x1080', panel: 'IPS', ports: 'HDMI, DP, VGA' },
    defaultWarrantyMonths: 36,
  },
  {
    key: 'u2723qe',
    categoryKey: 'monitor',
    manufacturer: 'Dell',
    modelName: 'UltraSharp U2723QE',
    specs: {
      screenInches: 27,
      resolution: '3840x2160',
      panel: 'IPS Black',
      ports: 'USB-C, HDMI, DP',
    },
    defaultWarrantyMonths: 36,
  },
  {
    key: 'e24-30',
    categoryKey: 'monitor',
    manufacturer: 'LG',
    modelName: '24BP450Y',
    specs: { screenInches: 24, resolution: '1920x1080', panel: 'IPS', ports: 'HDMI, DP' },
    defaultWarrantyMonths: 36,
  },
  {
    key: 'wd19s',
    categoryKey: 'dock',
    manufacturer: 'Dell',
    modelName: 'WD19S Dock 130W',
    specs: { power: '130W', ports: '2x DP, HDMI, 3x USB-A, USB-C, RJ45' },
    defaultWarrantyMonths: 36,
  },
  {
    key: 'lenovo-dock',
    categoryKey: 'dock',
    manufacturer: 'Lenovo',
    modelName: 'ThinkPad USB-C Dock Gen 2',
    specs: { power: '90W', ports: '2x DP, HDMI, 4x USB-A, RJ45' },
    defaultWarrantyMonths: 36,
  },
  {
    key: 'jabra-65',
    categoryKey: 'headset',
    manufacturer: 'Jabra',
    modelName: 'Evolve2 65',
    specs: {
      connection: 'Bluetooth + USB-A dongle',
      microphone: 'Noise cancelling',
      wireless: true,
    },
    defaultWarrantyMonths: 24,
  },
  {
    key: 'logi-h390',
    categoryKey: 'headset',
    manufacturer: 'Logitech',
    modelName: 'H390 USB Headset',
    specs: { connection: 'USB-A', microphone: 'Noise cancelling', wireless: false },
    defaultWarrantyMonths: 24,
  },
  {
    key: 'dell-65w',
    categoryKey: 'charger',
    manufacturer: 'Dell',
    modelName: '65W USB-C Adapter',
    specs: { power: '65W', connector: 'USB-C' },
    defaultWarrantyMonths: 12,
  },
  {
    key: 'logi-mk270',
    categoryKey: 'peripheral',
    manufacturer: 'Logitech',
    modelName: 'MK270 Wireless Combo',
    specs: { connection: '2.4GHz USB receiver', includes: 'Keyboard and mouse' },
    defaultWarrantyMonths: 12,
  },
];

export const DEPARTMENTS = [
  'Engineering',
  'Product',
  'Design',
  'Sales',
  'Marketing',
  'Finance',
  'People Operations',
  'Customer Success',
  'IT',
] as const;

export const DESIGNATIONS_BY_DEPARTMENT: Record<string, readonly string[]> = {
  Engineering: [
    'Software Engineer',
    'Senior Software Engineer',
    'Engineering Manager',
    'QA Engineer',
    'DevOps Engineer',
  ],
  Product: ['Product Manager', 'Senior Product Manager', 'Product Analyst'],
  Design: ['Product Designer', 'Senior Product Designer', 'UX Researcher'],
  Sales: ['Account Executive', 'Sales Development Rep', 'Regional Sales Manager'],
  Marketing: ['Marketing Associate', 'Content Strategist', 'Growth Marketer'],
  Finance: ['Financial Analyst', 'Accounts Executive', 'Finance Manager'],
  'People Operations': ['HR Business Partner', 'Talent Acquisition Specialist', 'HR Generalist'],
  'Customer Success': ['Customer Success Manager', 'Support Engineer', 'Onboarding Specialist'],
  IT: ['IT Support Engineer', 'IT Administrator', 'Systems Engineer'],
};

export const FIRST_NAMES = [
  'Aarav',
  'Aditi',
  'Advait',
  'Akanksha',
  'Ananya',
  'Arjun',
  'Bhavya',
  'Chetan',
  'Deepika',
  'Dhruv',
  'Farhan',
  'Gaurav',
  'Harshita',
  'Ishaan',
  'Jyoti',
  'Kabir',
  'Kavya',
  'Lakshmi',
  'Manish',
  'Meera',
  'Naveen',
  'Neha',
  'Nikhil',
  'Pallavi',
  'Pranav',
  'Priya',
  'Rahul',
  'Rashmi',
  'Rohan',
  'Ruchi',
  'Sameer',
  'Sanjana',
  'Shreya',
  'Siddharth',
  'Sneha',
  'Tanvi',
  'Tarun',
  'Uday',
  'Varun',
  'Vidya',
  'Vikram',
  'Vishal',
  'Yash',
  'Zara',
  'Anjali',
  'Rajesh',
  'Kiran',
  'Nandini',
  'Abhishek',
  'Divya',
] as const;

export const LAST_NAMES = [
  'Sharma',
  'Verma',
  'Iyer',
  'Nair',
  'Reddy',
  'Patel',
  'Singh',
  'Khan',
  'Menon',
  'Gupta',
  'Joshi',
  'Kulkarni',
  'Desai',
  'Bose',
  'Chatterjee',
  'Malhotra',
  'Kapoor',
  'Rao',
  'Pillai',
  'Bhatt',
  'Chauhan',
  'Saxena',
  'Mishra',
  'Tiwari',
  'Agarwal',
  'Banerjee',
  'Dutta',
  'Ghosh',
  'Jain',
  'Kaur',
] as const;
